# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SummitCli < Formula
  desc "This is the Summit CLI, a command-line tool for using the Summit API."
  homepage "https://github.com/cloudfactory/summit-public/tree/main/cli"
  version "2.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudfactory/summit-public/releases/download/summit-cli-v2.2.0/summit-cli_2.2.0_darwin_x86_64.tar.gz"
      sha256 "1b4ea5b012f2f99ecc334f8f2550267bb6d7965e0557289a0176d0b18bce0ae4"

      def install
        bin.install "summit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudfactory/summit-public/releases/download/summit-cli-v2.2.0/summit-cli_2.2.0_darwin_arm64.tar.gz"
      sha256 "797f3238341b06e154adfe93a3c3a41147cb8116e1e96e77653086160714b320"

      def install
        bin.install "summit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudfactory/summit-public/releases/download/summit-cli-v2.2.0/summit-cli_2.2.0_linux_x86_64.tar.gz"
      sha256 "245c3c1fed8cb112d49e04faec62390db588eb9b1942e12931ba9caff032c3e9"
      def install
        bin.install "summit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudfactory/summit-public/releases/download/summit-cli-v2.2.0/summit-cli_2.2.0_linux_arm64.tar.gz"
      sha256 "e85260c5c06465d3a6fb885efa3f4b09aab558f6ca0b419ac33b66cad9409f12"
      def install
        bin.install "summit"
      end
    end
  end
end
